name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  lint-test-build:
    runs-on: ${{ matrix.os }}
    needs:
      - create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: v2-${{ runner.os }}-release-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            v2-${{ runner.os }}-release
            v2-${{ runner.os }}
      - name: Setup
        run: rustup component add clippy
      - name: Lint
        run: cargo clippy
      - name: Run tests
        run: cargo test
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: consulator-${{ runner.os }}
          path: target/release/consulator
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/release/consulator
          asset_name: consulator-${{ runner.os }}
          asset_content_type: application/octet-stream
